Repository fivejars/openy_gated_content, pull requests merged in 2020-08, with the labels that each got.

#72 [VYMCA-66] Zoom embed
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/ZoomIframe.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/scss/views/_virtual-meeting-page.scss
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: FiveJars, REVIEWED, TESTED

#77 [VYMCA-67] Add thumbnail upload feature to video
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/views.view.virtual_y_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
  modules/openy_gc_auth/openy_gc_auth.routing.yml
  modules/openy_gc_demo/assets/images/bootcamp-challenge.png
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_file.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_image.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.teaser.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_image.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_image.yml
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.install
  openy_gated_content.permissions.yml
  openy_gated_content.routing.yml
Labels: FiveJars, REVIEWED, TESTED

#78 removed file_entity module from dependencies
  composer.json
  modules/openy_gc_log/config/install/file_entity.type.archive.yml
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.info.yml
  modules/openy_gc_log/openy_gc_log.links.menu.yml
  modules/openy_gc_log/openy_gc_log.permissions.yml
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/LogEntityAccessControlHandler.php
Labels: IXM, REVIEWED, TESTED

#79 [VYMCA-68] Shared content
  modules/openy_gc_shared_content/README.md
  modules/openy_gc_shared_content/config/install/openy_gc_shared_content.settings.yml
  modules/openy_gc_shared_content/config/install/openy_gc_shared_content.shared_content_source_server.openy.yml
  modules/openy_gc_shared_content/config/schema/shared_content_source_server.schema.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.info.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.links.action.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.links.menu.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.links.task.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.module
  modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.services.yml
  modules/openy_gc_shared_content/src/Annotation/SharedContentSourceType.php
  modules/openy_gc_shared_content/src/Controller/PreviewController.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServer.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServerInterface.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServerListBuilder.php
  modules/openy_gc_shared_content/src/Form/SettingsForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerDeleteForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
  modules/openy_gc_shared_content/src/Plugin/Derivative/SourceServerLocalTasks.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeInterface.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeManager.php
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--gc-video.html.twig
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--vy-blog-post.html.twig
  modules/openy_gc_shared_content_server/config/install/rest.resource.shared_source_create.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.links.menu.yml
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSourceViewsData.php
  modules/openy_gc_shared_content_server/src/Form/SharedContentSourceDeleteForm.php
  modules/openy_gc_shared_content_server/src/Plugin/rest/resource/SharedSourceCreate.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceAccessControlHandler.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceHtmlRouteProvider.php
  openy_gated_content.libraries.yml
Labels: NEEDS REVIEW, NEEDS TESTING

#83 [VYMCA-68] Add filter by field_gc_share to JSON API request
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
Labels: FiveJars

#84 Shared content feature
  js/gated-content/.gitignore
  modules/openy_gc_shared_content/README.md
  modules/openy_gc_shared_content/config/install/openy_gc_shared_content.shared_content_source_server.openy.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_eventinstance_share.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_eventinstance_unshare.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_eventseries_share.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_eventseries_unshare.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_node_share.yml
  modules/openy_gc_shared_content/config/install/system.action.gc_node_unshare.yml
  modules/openy_gc_shared_content/config/schema/shared_content_source_server.schema.yml
  modules/openy_gc_shared_content/config/update/views.view.event_series.yml
  modules/openy_gc_shared_content/config/update/views.view.events.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.info.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.install
  modules/openy_gc_shared_content/openy_gc_shared_content.links.action.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.links.menu.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.links.task.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.module
  modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.services.yml
  modules/openy_gc_shared_content/src/Annotation/SharedContentSourceType.php
  modules/openy_gc_shared_content/src/Controller/PreviewController.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServer.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServerInterface.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServerListBuilder.php
  modules/openy_gc_shared_content/src/Form/SettingsForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerDeleteForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
  modules/openy_gc_shared_content/src/Plugin/Action/EventinstanceShareToVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/EventinstanceUnshareFromVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/EventseriesShareToVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/EventseriesUnshareFromVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/NodeShareToVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/NodeUnshareFromVirtualY.php
  modules/openy_gc_shared_content/src/Plugin/Action/ShareToVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/Action/UnshareFromVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/Derivative/SourceServerLocalTasks.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeInterface.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeManager.php
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--gc-video.html.twig
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--vy-blog-post.html.twig
  modules/openy_gc_shared_content_server/config/install/rest.resource.shared_source_create.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.info.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.links.action.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.links.menu.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.permissions.yml
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/Form/SharedContentSourceForm.php
  modules/openy_gc_shared_content_server/src/Form/SharedContentSourceSettingsForm.php
  modules/openy_gc_shared_content_server/src/Plugin/rest/resource/SharedSourceCreate.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceAccessControlHandler.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceHtmlRouteProvider.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
  modules/openy_gc_shared_content_server/src/SourceRepository.php
  openy_gated_content.libraries.yml
Labels: FiveJars, IXM

#85 [VYMCA-68] Fix url for token generating
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
Labels: FiveJars

#87 [Shared content] PR review comments fix
  modules/openy_gc_shared_content/openy_gc_shared_content.info.yml
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
  modules/openy_gc_shared_content/src/Plugin/Action/ShareToVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/Action/UnshareFromVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
Labels: FiveJars

#88 Fix of bugs + code review fixes
  modules/openy_gc_shared_content/config/install/openy_gc_shared_content.shared_content_source_server.openy.yml
  modules/openy_gc_shared_content/openy_gc_shared_content.info.yml
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
  modules/openy_gc_shared_content/src/Plugin/Action/ShareToVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/Action/UnshareFromVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_blog.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_video.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_category.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_equipment.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_level.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_blog_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_blog.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_video.yml
  modules/openy_gc_shared_content_server/src/Plugin/migrate_plus/data_parser/VirtualYJson.php
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
Labels: IXM, REVIEWED

#92 Fix cs errors
  modules/openy_gc_log/openy_gc_log.install
Labels: FiveJars, NEEDS TESTING, REVIEWED
