Repository fivejars/openy_gated_content, pull requests merged in 2020-05, with the labels that each got.

#1 Setup builds
  .gitignore
  .phpcs.xml
  README.md
  composer.json
  config/install/paragraphs.paragraphs_type.gated_content.yml
  js/gated-content/.browserslistrc
  js/gated-content/.editorconfig
  js/gated-content/.eslintrc.js
  js/gated-content/.gitignore
  js/gated-content/README.md
  js/gated-content/babel.config.js
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/App.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/main.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/views/Home.vue
  js/gated-content/vue.config.js
  modules/openy_gc_demo/content/node/b48f9ebf-4737-4d1a-8304-d3ebb4b5e1c2.json
  modules/openy_gc_demo/content/paragraph/844397f8-33c2-4a45-a3ec-bc7da4023f8d.json
  modules/openy_gc_demo/openy_gc_demo.info.yml
  modules/openy_gc_demo/openy_gc_demo.module
  openy_gated_content.info.yml
  openy_gated_content.libraries.yml
  openy_gated_content.module
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, REVIEWED, TESTED, good first issue

#3 [VYMCA-3] Add openy_gc_storage module with node types and taxonomy for GC
  modules/openy_gc_demo/openy_gc_demo.info.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.teaser.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.taxonomy_term.gc_category.default.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_category.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_description.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_duration.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_equipment.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_instructor.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_level.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_media.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_category.field_gc_category_media.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_category.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_description.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_duration.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_instructor.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_level.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_media.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_category_media.yml
  modules/openy_gc_storage/config/install/language.content_settings.node.gc_video.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_category.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_equipment.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_instructor.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_level.yml
  modules/openy_gc_storage/config/install/node.type.gc_video.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_category.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_equipment.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_instructor.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_level.yml
  modules/openy_gc_storage/openy_gc_storage.features.yml
  modules/openy_gc_storage/openy_gc_storage.info.yml
Labels: FiveJars, REVIEWED, TESTED

#4 [VYMCA-8] Base JS auth component
  README.md
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/App.vue
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/LogoutLink.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/auth/DummyAuth.vue
  js/gated-content/src/main.js
  js/gated-content/src/router/index.js
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth.js
  js/gated-content/src/store/modules/auth/dummy.js
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/Login.vue
  js/gated-content/src/views/NotFound.vue
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#5 [VYMCA-4] Configure Live Stream
  composer.json
  modules/openy_gc_demo/content/eventseries/b00e1c2a-6ab6-4b67-823a-0e63c5c75aef.json
  modules/openy_gc_demo/content/media/cd3b0066-d52e-4f40-aadd-dd75184a13bc.json
  modules/openy_gc_demo/content/node/12652a96-2b05-4909-a5d6-bc1a1d7564d0.json
  modules/openy_gc_demo/content/node/5c1b8fdb-f986-4ad0-a19e-1e4da591b3d1.json
  modules/openy_gc_demo/content/taxonomy_term/0549d7ef-53a1-4ee5-aa21-0565bf57a663.json
  modules/openy_gc_demo/content/taxonomy_term/18701c2e-5e5b-4a4e-a30d-69d1326263a2.json
  modules/openy_gc_demo/content/taxonomy_term/2b80f92d-37cb-48d5-a6f4-c91160d91f5d.json
  modules/openy_gc_demo/content/taxonomy_term/31877582-6c0c-4cba-897b-98c6cccfecb3.json
  modules/openy_gc_demo/content/taxonomy_term/3852ac23-0979-4020-a8cb-67fc2a960e15.json
  modules/openy_gc_demo/content/taxonomy_term/3dc43b72-a50d-4f2a-9b5e-0d3dbfcea987.json
  modules/openy_gc_demo/content/taxonomy_term/4ca14d82-e7bb-405f-854c-0a8c53a1cca1.json
  modules/openy_gc_demo/content/taxonomy_term/4d7e37a0-e5ce-46a2-be75-4a160ad17828.json
  modules/openy_gc_demo/content/taxonomy_term/53fa9c1f-5710-4c37-84b0-048407a978c5.json
  modules/openy_gc_demo/content/taxonomy_term/6d3e8398-2e3f-4cf1-affe-cc452555a548.json
  modules/openy_gc_demo/content/taxonomy_term/8b90dc7a-8d12-4d06-b68e-6d2fc86cb193.json
  modules/openy_gc_demo/content/taxonomy_term/aefaa5cc-85d6-47e6-b836-42d705483f24.json
  modules/openy_gc_demo/content/taxonomy_term/af6076b4-b342-45ff-a5f8-aecdf0cf2efa.json
  modules/openy_gc_demo/content/taxonomy_term/b0fc6653-f9fb-4a72-a348-c0cfb433aa74.json
  modules/openy_gc_demo/content/taxonomy_term/cbd959dd-ee4c-4db6-9da2-20f64ee3eb08.json
  modules/openy_gc_demo/content/taxonomy_term/d2026d81-6be8-45ca-b029-5cfee9729eb8.json
  modules/openy_gc_demo/content/taxonomy_term/da1a9ced-342a-422d-a684-9cec8e4f7a40.json
  modules/openy_gc_demo/content/taxonomy_term/df4b42d2-01f3-4925-b6b2-7b5db6dbf813.json
  modules/openy_gc_demo/openy_gc_demo.info.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.default.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_media.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_category.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_description.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_media.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_title.yml
  modules/openy_gc_storage/config/install/recurring_events.eventinstance_type.live_stream.yml
  modules/openy_gc_storage/config/install/recurring_events.eventseries_type.live_stream.yml
  modules/openy_gc_storage/openy_gc_storage.info.yml
  modules/openy_gc_storage/openy_gc_storage.install
  modules/openy_gc_storage/openy_gc_storage.services.yml
  modules/openy_gc_storage/src/Routing/StorageRouteSubscriber.php
Labels: FiveJars, REVIEWED, TESTED

#6 [VYMCA-5] [VYMCA-6] Authentication system: Base module and admin UI
  modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.provider.dummy.yml
  modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.settings.yml
  modules/openy_gc_auth/modules/openy_gc_auth_example/openy_gc_auth_example.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Plugin/GCIdentityProvider/Example.php
  modules/openy_gc_auth/openy_gc_auth.info.yml
  modules/openy_gc_auth/openy_gc_auth.links.menu.yml
  modules/openy_gc_auth/openy_gc_auth.routing.yml
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/Annotation/GCIdentityProvider.php
  modules/openy_gc_auth/src/Form/GCAuthSettingsForm.php
  modules/openy_gc_auth/src/Form/GCIdentityProviderEditForm.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderManager.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_demo/openy_gc_demo.info.yml
  openy_gated_content.info.yml
  openy_gated_content.module
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, REVIEWED, TESTED

#7 [VYMCA-11] Base for the Home page and Individual Video pages
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/client/index.js
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/components/auth/DummyAuth.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/store/modules/auth/dummy.js
  js/gated-content/src/views/Login.vue
  js/gated-content/src/views/VideoPage.vue
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, REVIEWED, TESTED

#9 video page
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/components/YoutubePlayButton.vue
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/videopage/videopage.scss
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, REVIEWED, TESTED

#8 [VYMCA-13] CSV file auth plugin
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/components/ReCaptcha.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth/custom.js
  js/gated-content/src/views/Login.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration_group.gc_auth.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/rest.resource.openy_gc_auth_custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUserInterface.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/ImportCsvBatch.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/source/CSVLimit.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.settings.yml
  modules/openy_gc_demo/openy_gc_demo.info.yml
Labels: FiveJars, NEEDS REVIEW, TESTED

#12 Add level and equipment fields
  js/gated-content/src/views/LiveStreamPage.vue
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_level.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_equipment.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_level.yml
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#11 live streams teasers styles and videos teaser duration calc
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/main.js
  js/gated-content/src/scss/components/_live-stream-listing.scss
  js/gated-content/src/scss/components/_live-stream-teaser.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/videopage/videopage.scss
  js/gated-content/src/scss/views/_home.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/scss/widgets/_video-level.scss
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, REVIEWED, TESTED

#13 [VYMCA-18] Add reCaptcha to login form
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/LogoutLink.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_login.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/Login.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/vue.config.js
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_instructor.yml
  openy_gated_content.info.yml
  openy_gated_content.libraries.yml
  openy_gated_content.module
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#14 [VYMCA-19] Close access to video, live stream pages
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/VideoListing.vue
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.permissions.yml
  openy_gated_content.services.yml
  src/EventSubscriber/GatedContentSubscriber.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING
