Repository fivejars/openy_gated_content, pull requests merged in 2020-07, with the labels that each got.

#48 [VYMCA-52] Hide video categories without videos
  js/gated-content/src/views/VideoCategoriesListing.vue
  openy_gated_content.routing.yml
  src/Controller/CategoriesController.php
Labels: FiveJars, REVIEWED, TESTED

#51 fix deepcode review notices and default content ids
  js/gated-content/src/components/auth/DummyAuth.vue
  js/gated-content/src/views/BlogPage.vue
  modules/openy_gc_demo/content/node/b48f9ebf-4737-4d1a-8304-d3ebb4b5e1c2.json
  modules/openy_gc_demo/content/paragraph/844397f8-33c2-4a45-a3ec-bc7da4023f8d.json
Labels: IXM, NEEDS TESTING, REVIEWED

#50 Show blogs under live streams on front page
  js/gated-content/src/views/Home.vue
Labels: FiveJars, NEEDS TESTING, REVIEWED

#55 Added Virtual Y blog migration
  modules/openy_gc_demo/assets/images/baylee-gramling-R5eoT-c-jkY-unsplash.jpg
  modules/openy_gc_demo/assets/images/david-marcu-69433-unsplash.jpg
  modules/openy_gc_demo/assets/images/joan-azeka-bg43g7xTu2M-unsplash.jpg
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_file.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_image.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
Labels: IXM, REVIEWED

#61 Buttons fixes
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/AddToCalendar.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_demo/README.md
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_color.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_landing.yml
  modules/openy_gc_demo/openy_gc_demo.info.yml
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#64 Rebuilt migration from fly_paragraph to dependencies
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_landing.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_banner.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_gated_content.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_gated_content_login.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_small_banner.yml
  modules/openy_gc_demo/openy_gc_demo.info.yml
Labels: IXM, REVIEWED, TESTED

#63 Fix empty blocks message
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingListingPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING, enhancement

#67 [VYMCA-65] Remove unpublished entities from listings
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  src/Controller/CategoriesController.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING, bug

#68 [VYMCA-64] CSV Security Enhancement
  README.md
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/components/auth/CustomAuthEmailConfirm.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/modules/auth/custom.js
  js/gated-content/src/views/Login.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/rest.resource.openy_gc_auth_custom_confirm.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/views.view.virtual_y_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/ErrorResponseTrait.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthConfirm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_auth_custom_user.yml
  patches/video_embed_field_vimeo_private_videos.patch
Labels: FiveJars, NEEDS REVIEW, TESTED

#70 Logger archive for Virtual Y
  composer.json
  modules/openy_gc_log/config/install/file_entity.type.archive.yml
  modules/openy_gc_log/openy_gc_log.info.yml
  modules/openy_gc_log/openy_gc_log.module
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/LogArchiver.php
Labels: IXM, NEEDS TESTING, REVIEWED

#71 Styled personify error message + new membership check logic
  js/gated-content/.gitignore
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/auth/PersonifyAuth.vue
  js/gated-content/src/scss/views/_login.scss
  modules/openy_gc_auth/modules/openy_gc_auth_personify/config/install/openy_gc_auth.provider.personify.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.install
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
Labels: IXM, NEEDS REVIEW
