Repository fivejars/openy_gated_content, pull requests merged in 2020-12, with the labels that each got.

#180 Add PR template
  .github/pull_request_template.md
Labels: REVIEWED

#177 Featured headline
  README.md
  assets/img/paragraph-headline.png
  config/install/core.entity_form_display.paragraph.gated_content.default.yml
  config/install/core.entity_view_display.paragraph.gated_content.default.yml
  config/install/field.field.paragraph.gated_content.field_prgf_description.yml
  config/install/field.field.paragraph.gated_content.field_prgf_image.yml
  config/install/field.field.paragraph.gated_content.field_prgf_link.yml
  config/install/field.field.paragraph.gated_content.field_prgf_title.yml
  config/install/image.style.virtual_y_paragraph_headline.yml
  css/styles.css
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/ParagraphHeadline.vue
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/components/_paragraph-headline.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/headline.js
  js/gated-content/src/views/Home.vue
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_gated_content.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_small_banner.yml
  openy_gated_content.install
  openy_gated_content.module
  openy_gated_content.post_update.php
  templates/paragraph--gated-content.html.twig
Labels: IXM, NEEDS TESTING, REVIEWED

#175 Daxko SSO active status check fix
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/openy_gc_auth.provider.daxko_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.post_update.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/VirtualYDaxkoSSOLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
Labels: IXM, NEEDS TESTING, REVIEWED

#184 [VYMCA-102] Add the entity title, instructor name and entity create d…
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.api.php
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/LogArchiver.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#182 [VYMCA-104] Add Favorites option
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/AddToFavorite.vue
  js/gated-content/src/components/Modal.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/CategoryTeaser.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/mixins/FavoritesMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_favorites.scss
  js/gated-content/src/scss/components/_modal.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_favorites_page.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/favorites.js
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoriesListing.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  openy_gated_content.install
  openy_gated_content.permissions.yml
  openy_gated_content.routing.yml
  src/Controller/FavoritesController.php
  src/Entity/VyFavoriteItem.php
  src/VyFavoriteItemInterface.php
  src/VyFavoriteItemStorageSchema.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#179 Modifications on form label for having daxko barcode config values.
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
Labels: NEEDS TESTING

#183 Top Menu
  assets/js/openy_rose.behaviors.js
  config/install/openy_gated_content.settings.yml
  css/styles.css
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/LogoutLink.vue
  js/gated-content/src/components/TopMenu.vue
  js/gated-content/src/components/svg/CategoriesIcon.vue
  js/gated-content/src/components/svg/CloseIcon.vue
  js/gated-content/src/components/svg/FavoritesIcon.vue
  js/gated-content/src/components/svg/LogoutIcon.vue
  js/gated-content/src/components/svg/MenuIcon.vue
  js/gated-content/src/components/svg/ScheduleIcon.vue
  js/gated-content/src/main.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/components/_top-menu.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/theme_overrides.scss
  modules/openy_gc_demo/README.md
  openy_gated_content.install
  openy_gated_content.libraries.yml
  openy_gated_content.module
  src/Form/GCSettingsForm.php
Labels: IXM, NEEDS TESTING, REVIEWED

#196 Sync enabled fields
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
Labels: IXM, NEEDS TESTING, REVIEWED

#174 [VYMCA-106] Implement "Scroll to top" button
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/ScrollToTop.vue
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/theme_overrides.scss
Labels: FiveJars, NEEDS TESTING, REVIEWED

#193 Resolved outlook spaces issue.
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/AddToCalendar.vue
Labels: REVIEWED, TESTED

#200 [VYMCA-108] Disable /user/{id}/edit page for virtual y users
  openy_gated_content.services.yml
  src/EditUserAccountAccessCheck.php
  src/EventSubscriber/RouteSubscriber.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#197 Event teaser, video teaser, blog teaser, four columns layout
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/assets/svg/clock-regular.svg
  js/gated-content/src/assets/svg/date-icon.svg
  js/gated-content/src/assets/svg/favorites-outlined.svg
  js/gated-content/src/assets/svg/favorites-solid.svg
  js/gated-content/src/assets/svg/instructor-icon.svg
  js/gated-content/src/components/AddToFavorite.vue
  js/gated-content/src/components/PageHeader.vue
  js/gated-content/src/components/SvgIcon.vue
  js/gated-content/src/components/TopMenu.vue
  js/gated-content/src/components/YoutubePlayButton.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/scss/_fonts.scss
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/components/_blog-listing.scss
  js/gated-content/src/scss/components/_blog-teaser.scss
  js/gated-content/src/scss/components/_event-teaser.scss
  js/gated-content/src/scss/components/_favorites.scss
  js/gated-content/src/scss/components/_page-header.scss
  js/gated-content/src/scss/components/_paragraph-headline.scss
  js/gated-content/src/scss/components/_svg-icon.scss
  js/gated-content/src/scss/components/_top-menu.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/layout/four-columns.scss
  js/gated-content/src/scss/widgets/_empty-listing.scss
  js/gated-content/src/scss/widgets/_listing-header.scss
  js/gated-content/src/scss/widgets/_teaser.scss
  js/gated-content/src/views/Home.vue
  openy_gated_content.install
Labels: IXM, NEEDS TESTING, REVIEWED

#186 Added addiittional info to the Y-USA form
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
Labels: IXM, NEEDS TESTING, REVIEWED

#188 Exclude virtual_ymca_editor from category access check 2
  src/Controller/CategoriesController.php
  src/GCUserService.php
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
  src/SegmentContentAccessCheck.php
  src/VirtualYAccessTrait.php
Labels: IXM, TESTED

#199 [VYMCA-110] Categories listing page + videos listing page
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/category/CategoriesListing.vue
  js/gated-content/src/components/category/CategoryTeaser.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/modal/Modal.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/mixins/FilterAndSortMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_favorites.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_favorites_page.scss
  js/gated-content/src/store/modules/favorites.js
  js/gated-content/src/views/BlogsListingPage.vue
  js/gated-content/src/views/CategoriesListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/VideosListingPage.vue
  openy_gated_content.routing.yml
  src/Controller/CategoriesController.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#198 [VYMCA-107] Implement Schedule page
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/ScheduleEventCard.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/theme_overrides.scss
  js/gated-content/src/scss/views/_schedule-page.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/SchedulePage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: FiveJars, REVIEWED, TESTED

#208 Code from master
  .github/pull_request_template.md
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/AddToCalendar.vue
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/openy_gc_auth.provider.daxko_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.post_update.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/VirtualYDaxkoSSOLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.api.php
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
  openy_gated_content.services.yml
  src/Controller/CategoriesController.php
  src/EditUserAccountAccessCheck.php
  src/EventSubscriber/RouteSubscriber.php
  src/GCUserService.php
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
  src/SegmentContentAccessCheck.php
  src/VirtualYAccessTrait.php
Labels: NEEDS REVIEW

#205 [VYMCA-113] Update demo content for VY.
  modules/openy_gc_demo/assets/images/cardio-workout-main.jpg
  modules/openy_gc_demo/assets/images/forever-well-category.jpg
  modules/openy_gc_demo/assets/images/healthy-eating.png
  modules/openy_gc_demo/assets/images/man-yoga-meditation.jpg
  modules/openy_gc_demo/assets/images/strength-training-classes.jpg
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_file.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_category.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_equipment.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_image.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
Labels: FiveJars, NEEDS TESTING, REVIEWED

#207 Fix reclique logger
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/openy_gc_auth_reclique.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/RecliqueClientService.php
Labels: NEEDS TESTING, REVIEWED

#194 Description length issue for add to calendar.
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: NEEDS TESTING, REVIEWED

#206 Train credentials at Daxko
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
Labels: IXM, NEEDS TESTING, REVIEWED

#201 Shared content: remaining items
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
Labels: IXM, REVIEWED

#210 Demo content fix
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml
Labels: FiveJars, NEEDS TESTING, REVIEWED

#192 GC AUTH YUSA: Add virtual_y role if user is active but not mapped
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/EventSubscriber/GCAuthYUSAUserLoginSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/YUSAClientService.php
Labels: REVIEWED, TESTED

#215 Added library that fixes hash errors
  assets/js/hash.behaviors.js
  openy_gated_content.libraries.yml
Labels: IXM, NEEDS TESTING, REVIEWED

#202 Fixed caching issue for Daxko SSO
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/widgets/button.scss
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.module
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Form/VirtualYDaxkoSSOLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
Labels: IXM, REVIEWED, TESTED

#216 1, 2, 3 columns for events listings
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/mixins/ListingMixin.js
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/layout/one-columns.scss
  js/gated-content/src/scss/layout/three-columns.scss
  js/gated-content/src/scss/layout/two-columns.scss
  js/gated-content/src/scss/widgets/_teaser.scss
Labels: IXM, REVIEWED, TESTED

#212 [VYMCA-114] Add require_email_verification setting
  modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#217 Hotfix/different top menu height
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/components/_top-menu.scss
  js/gated-content/src/scss/theme_overrides.scss
Labels: FiveJars, NEEDS TESTING, REVIEWED

#220 Fix days and hours color selection
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/SchedulePage.vue
Labels: FiveJars, REVIEWED, TESTED, bug

#222 Deleted openy_gc_auth_example dependency
  modules/openy_gc_demo/openy_gc_demo.info.yml
Labels: IXM, REVIEWED

#223 Update 'starts in' template to display only days count for durations higher then 2 days
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/mixins/EventMixin.js
Labels: IXM, NEEDS REVIEW, TESTED

#224 mobile menu border color will follow link color from settings
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/components/_top-menu.scss
Labels: IXM, NEEDS REVIEW, TESTED
