Repository fivejars/openy_gated_content, pull requests merged in 2020-10, with the labels that each got.

#124 Bug fix
  openy_gated_content.install
  openy_gated_content.module
  src/Form/GCSettingsForm.php
Labels: IXM, REVIEWED, TESTED

#126 [VYMCA-84] Fix 404 pages for videos in blogs from menu
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_menu_link_main.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_small_banner.yml
  modules/openy_gc_shared_content/config/update/views.view.event_series.yml
  modules/openy_gc_shared_content/config/update/views.view.events.yml
Labels: FiveJars, REVIEWED, TESTED

#122 [VYMCA-74] Shared content security: fix for new permissions check
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/EventMixin.js
  modules/openy_gc_shared_content/openy_gc_shared_content.install
  modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml
  modules/openy_gc_shared_content/src/Controller/SharedContentProxyController.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  src/SegmentContentAccessCheck.php
Labels: FiveJars, REVIEWED, TESTED

#123 Add 'status' field to 'shared_content_source' entity type.
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
Labels: IXM, NEEDS TESTING, REVIEWED

#125 Add custom event for user login, add example subscriber for changing roles, move everything related to authorize to a new custom service
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/Event/GCUserLoginEvent.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  modules/openy_gc_log/README.md
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/EventSubscriber/GCLogUserLoginSubscriber.php
Labels: IXM, TESTED

#128 Fix clock icon for all 3 themes
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: IXM, TESTED

#130 VY: Add Personify try again form with redirects and messages when no active membership
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Form/VirtualYPersonifyTryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
Labels: IXM

#129 Bug fixes 1
  README.md
  modules/openy_gc_auth/README.md
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_virtual_meeting.yml
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.install
  openy_gated_content.info.yml
  openy_gated_content.install
  openy_gated_content.module
  openy_gated_content.post_update.php
Labels: IXM, NEEDS REVIEW

#132 Fixed default permissions for Event Instance.
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.module
Labels: IXM, NEEDS TESTING, REVIEWED

#133 Fixed bug with infinite loop at post update
  openy_gated_content.post_update.php
Labels: IXM, REVIEWED, bug

#136 Small issues fixes
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/ZoomIframe.vue
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#135 VY: Make logout link configurable
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/LogoutLink.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: IXM, NEEDS TESTING, REVIEWED

#139 TEST CI
  .phpcs.xml
  composer.json
  js/gated-content/dist/gated-content.umd.min.js
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Form/VirtualYPersonifyTryAgainForm.php
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  modules/openy_gc_log/openy_gc_log.module
  modules/openy_gc_log/src/Controller/LogController.php
  modules/openy_gc_log/src/EventSubscriber/GCLogUserLoginSubscriber.php
  modules/openy_gc_log/src/Field/PayloadFieldItemList.php
  modules/openy_gc_log/src/Form/LogEntitySettingsForm.php
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/LogEntityListBuilder.php
  modules/openy_gc_log/src/Logger.php
  modules/openy_gc_shared_content_server/src/Controller/DownloadsIncrementController.php
  modules/openy_gc_shared_content_server/src/Form/SharedContentSourceForm.php
  modules/openy_gc_shared_content_server/src/Form/SharedContentSourceSettingsForm.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
  modules/openy_gc_shared_content_server/src/SourceRepository.php
  openy_gated_content.module
  src/SegmentContentAccessCheck.php
Labels: DO NOT MERGE

#140 [VYMCA-95] UI import issue fix for migrate_source_csv v3
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration_group.gc_auth.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/ImportCsvBatch.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/source/CSVLimit.php
  modules/openy_gc_log/src/Logger.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#141 Comma appears on video details page when only one category selected
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: FiveJars, REVIEWED, TESTED

#142 [VYMCA-91] Allow private link hashes for the embeddable Vimeo events
  src/Plugin/video_embed_field/Provider/VimeoEvent.php
Labels: FiveJars, REVIEWED, TESTED

#144 [VYMCA-90] Consider user roles in CategoriesController
  src/Controller/CategoriesController.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#138 YOPN-947 VY: Add Y-USA Authentication provider support
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/config/install/openy_gc_auth.provider.yusa.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.module
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/EventSubscriber/GCAuthYUSAUserLoginSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
  modules/openy_gc_auth/src/Event/GCUserLoginEvent.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  openy_gated_content.services.yml
  src/GCUserService.php
Labels: IXM, NEEDS WORK, REVIEWED, TESTED

#145 Backported fix
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
Labels: IXM, NEEDS REVIEW

#148 Hotfix
  js/gated-content/dist/gated-content.umd.min.js
  modules/openy_gc_auth/src/GCUserAuthorizer.php
Labels: FiveJars, NEEDS TESTING, REVIEWED, bug

#146 [VYMCA-97] Notifications for shared content server
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.module
  modules/openy_gc_shared_content_server/src/Plugin/rest/resource/SharedSourceCreate.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#147 VY: Add User Logout Event and Personify Subscriber for logout, rebuilt logout logic
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/LogoutLink.vue
  modules/openy_gc_auth/modules/openy_gc_auth_personify/config/install/openy_gc_auth_personify.settings.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/EventSubscriber/PersonifyUserLogoutSubscriber.php
  modules/openy_gc_auth/openy_gc_auth.routing.yml
  modules/openy_gc_auth/src/Controller/GCAuthController.php
  modules/openy_gc_auth/src/Event/GCUserLogoutEvent.php
Labels: IXM, NEEDS REVIEW

#149 [VYMCA-99] Implement export logs functionality
  composer.json
  modules/openy_gc_log/openy_gc_log.links.action.yml
  modules/openy_gc_log/openy_gc_log.links.menu.yml
  modules/openy_gc_log/openy_gc_log.module
  modules/openy_gc_log/openy_gc_log.routing.yml
  modules/openy_gc_log/src/Form/ManualExportForm.php
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/Logger.php
Labels: FiveJars, REVIEWED, TESTED

#150 VY: various improvements/bugfixes
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Form/VirtualYReCliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/config/install/openy_gc_auth.provider.yusa.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php
  openy_gated_content.install
Labels: IXM, NEEDS TESTING, REVIEWED

#152 Add uid data to the logs
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.routing.yml
  modules/openy_gc_log/src/Entity/LogEntity.php
  modules/openy_gc_log/src/EventSubscriber/GCLogUserLoginSubscriber.php
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/Logger.php
Labels: FiveJars, REVIEWED, TESTED

#151 [VYMCA-100] Sync option for CSV migration from UI
  composer.json
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/source/CSVLimit.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#153 VY: ReClique send email verification each time when user is login in
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/EventSubscriber/PersonifyUserLogoutSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/EventSubscriber/GCAuthReCliqueUserLoginSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Form/VirtualYReCliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/EventSubscriber/GCAuthYUSAUserLoginSubscriber.php
Labels: IXM, NEEDS TESTING, REVIEWED

#154 Reclique fix
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/openy_gc_auth_reclique.module
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/openy_gc_auth_reclique.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/EventSubscriber/GCAuthReCliqueUserLoginSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Form/VirtualYReCliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/RecliqueClientService.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/YUSAClientService.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_landing.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_gated_content.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_gated_content_login.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_blog_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_blog.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_video.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
  openy_gated_content.info.yml
Labels: IXM, NEEDS TESTING, REVIEWED

#155 [VYMCA-101] Hide category field on event view display due to an error
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.virtual_meeting.default.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING
