Repository fivejars/openy_gated_content, pull requests merged in 2020-09, with the labels that each got.

#94 [VYMCA-71] Hide unused content types from dashboard/configurable titles
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/mixins/SettingsMixin.js
  js/gated-content/src/views/BlogListingPage.vue
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingListingPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#93 YOPN-921 VY: Multiple Category Tags
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/VideoPage.vue
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_category.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: IXM, REVIEWED, TESTED

#101 [VYMCA-56] Improve disabling of pager links
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/Pagination.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/video/VideoListing.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#102 [YGBWSLA-166] Fix recaptcha error in custom login
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/Pagination.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/video/VideoListing.vue
Labels: NEEDS REVIEW, NEEDS TESTING

#98 Rearch: Close password reset and login form for virtual_y roles
  openy_gated_content.module
Labels: IXM, NEEDS TESTING, REVIEWED

#105 Update combine method for multi-value fields
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/JsonApiCombineMixin.js
Labels: NEEDS REVIEW, NEEDS TESTING

#104 [VYMCA-76] Categories enhancements for blogs and videos + Make event category multiple
  js/gated-content/.gitignore
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/mixins/JsonApiCombineMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/views/_category-page.scss
  js/gated-content/src/views/BlogListingPage.vue
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoriesListing.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_category.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.vy_blog_post.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.vy_blog_post.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.vy_blog_post.teaser.yml
  modules/openy_gc_storage/config/install/field.field.node.vy_blog_post.field_gc_video_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_category.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_category.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_category.yml
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.routing.yml
  src/Controller/CategoriesController.php
Labels: FiveJars, REVIEWED, TESTED

#107 [VYMCA-77] Display compatible video host sources in video field widget
  modules/openy_gc_storage/openy_gc_storage.module
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#99 Users rebuild preparation
  config/install/core.entity_form_display.paragraph.gated_content_login.default.yml
  config/install/core.entity_view_display.paragraph.gated_content_login.default.yml
  config/install/field.field.paragraph.gated_content_login.field_link_to_gated_content_app.yml
  config/install/field.storage.paragraph.field_link_to_gated_content_app.yml
  config/install/user.role.virtual_y.yml
  config/install/user.role.virtual_y_premium.yml
  config/install/user.role.virtual_y_trial.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/auth/DummyAuth.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth/dummy.js
  js/gated-content/src/views/Login.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Plugin/GCIdentityProvider/Example.php
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/Plugin/Block/VirtualYLoginBlock.php
  openy_gated_content.install
  src/Form/GCSettingsForm.php
  templates/paragraph--gated-content-login.html.twig
Labels: DO NOT MERGE, IXM

#106 Shared content stat
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content_server/config/install/views.view.virtual_y_shared_content_statistic.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.info.yml
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.module
  modules/openy_gc_shared_content_server/openy_gc_shared_content_server.routing.yml
  modules/openy_gc_shared_content_server/src/Controller/DownloadsIncrementController.php
Labels: IXM, NEEDS TESTING, REVIEWED

#111 Add recurring events series config and update hook.
  modules/openy_gc_storage/config/install/recurring_events.eventseries.config.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: REVIEWED, TESTED

#109 [VYMCA-79] New CSV auth for user segmentation
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.umd.min.js
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/rest.resource.openy_gc_auth_custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/rest.resource.openy_gc_auth_custom_confirm.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/views.view.virtual_y_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.post_update.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUserInterface.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/ErrorResponseTrait.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthConfirm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_auth/openy_gc_auth.module
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_auth/src/Plugin/Block/VirtualYLoginBlock.php
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_auth_custom_user_demo.yml
  modules/openy_gc_shared_content/src/Form/SettingsForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  openy_gated_content.install
  openy_gated_content.module
  openy_gated_content.post_update.php
  src/Form/GCSettingsForm.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#113 Some fixes
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/router/index.js
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth/custom.js
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.module
  src/Form/GCSettingsForm.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#114 Some fixes
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/views/_login.scss
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
Labels: IXM, NEEDS TESTING, REVIEWED

#116 Deprecated code deleting
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/ReCaptcha.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/components/auth/CustomAuthEmailConfirm.vue
  js/gated-content/src/components/auth/DaxkoBarcode.vue
  js/gated-content/src/components/auth/DaxkoSSO.vue
  js/gated-content/src/components/auth/PersonifyAuth.vue
  js/gated-content/src/plugins/log.js
  js/gated-content/src/router/index.js
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth.js
  js/gated-content/src/views/Login.vue
  js/gated-content/vue.config.js
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Plugin/GCIdentityProvider/DaxkoBarcode.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Plugin/GCIdentityProvider/Example.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.module
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#115 YOPN-927 VY: Rebuild user and node logging completely
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/plugins/log.js
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/Controller/LogController.php
  modules/openy_gc_log/src/Logger.php
Labels: IXM, REVIEWED, TESTED

#112 Add install instructions
  README.md
Labels: NEEDS WORK, documentation

#118 [VYMCA-74] Shared content security enhancements
  js/gated-content/dist/gated-content.umd.min.js
  modules/openy_gc_shared_content/openy_gc_shared_content.install
  modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml
  modules/openy_gc_shared_content/src/Controller/PreviewController.php
  modules/openy_gc_shared_content/src/Controller/SharedContentProxyController.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeInterface.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#117 User segmentation
  config/install/openy_gated_content.settings.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_virtual_meeting.yml
  openy_gated_content.info.yml
  openy_gated_content.install
  openy_gated_content.module
  openy_gated_content.post_update.php
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
  src/SegmentContentAccessCheck.php
Labels: IXM, REVIEWED, TESTED

#121 [VYMCA-82] Use syncSource option in UI migration
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/ImportCsvBatch.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#120 VY: update virtual_y_editor permissions
  config/install/user.role.virtual_ymca_editor.yml
  openy_gated_content.install
Labels: IXM, REVIEWED, TESTED
