Repository fivejars/openy_gated_content, pull requests merged in 2020-11, with the labels that each got.

#156 VY: add redirects for old links
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/router/index.js
Labels: IXM, REVIEWED, TESTED

#160 VY rebuild logout logic a bit
  config/install/openy_gated_content.settings.yml
  modules/openy_gc_auth/src/Controller/GCAuthController.php
  src/Form/GCSettingsForm.php
Labels: IXM, REVIEWED

#161 Added readme for new modules
  modules/openy_gc_auth/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/README.md
Labels: IXM, REVIEWED, documentation

#163 Security issue fix for custom auth provider
  modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
Labels: FiveJars, REVIEWED, TESTED, bug

#168 [VYMCA-102] Change the player and add video events logging
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/plugins/log.js
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/src/Entity/LogEntityInterface.php
  modules/openy_gc_log/src/Field/PayloadFieldItemList.php
Labels: FiveJars, REVIEWED, TESTED

#167 R1.2 - Personify SSO - Issue #52: Add Login form and options to redirect
  modules/openy_gc_auth/modules/openy_gc_auth_personify/config/install/openy_gc_auth.provider.personify.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.install
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Form/VirtualYPersonifyLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
Labels: IXM, NEEDS TESTING, REVIEWED

#171 VY: Add Autologout functionality
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCAuthManager.php
  modules/openy_gc_autologout/config/install/openy_gc_autologout.settings.yml
  modules/openy_gc_autologout/js/idle.min.js
  modules/openy_gc_autologout/js/openy_gc_autologout.js
  modules/openy_gc_autologout/openy_gc_autologout.info.yml
  modules/openy_gc_autologout/openy_gc_autologout.libraries.yml
  modules/openy_gc_autologout/openy_gc_autologout.links.menu.yml
  modules/openy_gc_autologout/openy_gc_autologout.module
  modules/openy_gc_autologout/openy_gc_autologout.permissions.yml
  modules/openy_gc_autologout/openy_gc_autologout.routing.yml
  modules/openy_gc_autologout/src/Controller/VirtualYAutologoutController.php
  modules/openy_gc_autologout/src/Form/VirtualYAutologoutSettingsForm.php
Labels: IXM, REVIEWED, TESTED

#173 Shared content fields cleanup improvement
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
Labels: FiveJars, REVIEWED, TESTED

#172 [VYMCA-105] Build an app to be able to work in the IE11
  js/gated-content/.browserslistrc
  js/gated-content/.postcssrc
  js/gated-content/babel.config.js
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/main.js
  js/gated-content/src/scss/components/_blog-listing.scss
  js/gated-content/src/scss/components/_category-listing.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/vue.config.js
  modules/openy_gc_log/js/logger.behaviors.js
Labels: FiveJars, NEEDS TESTING, REVIEWED

#159 Backport: force daxko redirect with no cache
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
Labels: IXM, NEEDS TESTING, REVIEWED

#166 Fix for page layout fix for blog posts without image.
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/BlogPage.vue
Labels: NEEDS TESTING, REVIEWED

#178 VY: fix personify user authorize after back redirect
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
Labels: IXM, NEEDS REVIEW, NEEDS TESTING
