Repository fivejars/openy_gated_content, pull requests merged in 2020-06, with the labels that each got.

#15 [VYMCA-21] Remove dependency to openy_focal_point
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/openy_gc_storage.info.yml
  openy_gated_content.info.yml
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#16 review fixes
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/client/index.js
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/scss/components/_live-stream-listing.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_home.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_level.yml
Labels: IXM, NEEDS TESTING, REVIEWED

#17 Small improvements
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/auth/CustomAuth.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/router/index.js
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#20 [VYMCA-28] Category image
  composer.json
  js/gated-content/src/components/CategoryTeaser.vue
  js/gated-content/src/mixins/JsonApiCombineMixin.js
  js/gated-content/src/views/VideoCategoriesListing.vue
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/image.style.gated_content_teaser.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_instructor.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_instructor.yml
  modules/openy_gc_storage/openy_gc_storage.info.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#21 Styles for categories page, Category page, Category filters for video…
  js/gated-content/src/components/CategoryTeaser.vue
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/components/_category-listing.scss
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_category-page.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoCategoriesListing.vue
  js/gated-content/src/views/VideoPage.vue
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_media.yml
Labels: IXM, REVIEWED, TESTED

#22 [VYMCA-27] Vimeo widget for application
  js/gated-content/package-lock.json
  js/gated-content/package.json
  js/gated-content/src/components/CategoryTeaser.vue
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/mixins/JsonApiCombineMixin.js
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  modules/openy_gc_demo/content/file/581596f7-2afa-4be1-9662-45d4c2772d60.json
  modules/openy_gc_demo/content/file/700edc95-34af-4e68-b999-ab569af3bb12.json
  modules/openy_gc_demo/content/media/2f38d23b-b256-4381-b643-3adcfce2e89a.json
  modules/openy_gc_demo/content/media/ccbb54fb-0929-411d-bcda-1ed74fd50676.json
  modules/openy_gc_demo/content/node/a92efdba-6ba8-42ea-aff9-3efff65fe092.json
  modules/openy_gc_demo/content/node/ffdb52cd-d51d-4216-ba6b-71719e15b569.json
  modules/openy_gc_demo/content/taxonomy_term/0549d7ef-53a1-4ee5-aa21-0565bf57a663.json
  modules/openy_gc_demo/content/taxonomy_term/31877582-6c0c-4cba-897b-98c6cccfecb3.json
  modules/openy_gc_demo/content/taxonomy_term/4ca14d82-e7bb-405f-854c-0a8c53a1cca1.json
  modules/openy_gc_demo/content/taxonomy_term/4d7e37a0-e5ce-46a2-be75-4a160ad17828.json
  modules/openy_gc_demo/content/taxonomy_term/aefaa5cc-85d6-47e6-b836-42d705483f24.json
  modules/openy_gc_demo/content/taxonomy_term/cbd959dd-ee4c-4db6-9da2-20f64ee3eb08.json
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#24 [VYMCA-27] Private videos support
  README.md
  js/gated-content/src/components/MediaPlayer.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#23 container on pages
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/scss/components/_category-listing.scss
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_home.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoCategoriesListing.vue
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, REVIEWED, TESTED

#25 [VYMCA-29] Add small banner with buttons to gated content
  modules/openy_gc_demo/content/node/b48f9ebf-4737-4d1a-8304-d3ebb4b5e1c2.json
  modules/openy_gc_demo/content/paragraph/844397f8-33c2-4a45-a3ec-bc7da4023f8d.json
  modules/openy_gc_demo/content/paragraph/ef77ce1c-d8e6-4eb4-9842-cd6b8ad92cd2.json
  modules/openy_gc_demo/content/taxonomy_term/049c3a61-574b-409d-b9a9-6146b2d231ff.json
Labels: FiveJars, REVIEWED, TESTED

#26 [VYMCA-30] Events not displayed for anonymous users
  openy_gated_content.module
Labels: FiveJars, REVIEWED, TESTED

#28 equipment check fix
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, REVIEWED, TESTED

#29 [VYMCA-36] Add support of Vimeo live streams
  js/gated-content/src/components/MediaPlayer.vue
  src/Plugin/video_embed_field/Provider/VimeoEvent.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#30 [VYMCA-33] [VYMCA-36] Latest videos/events if no featured results
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_image.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_image.yml
  openy_gated_content.module
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#32 vimeo player ratio, date filter styles, and hide left button for today
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/scss/components/_category-listing.scss
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_home.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, REVIEWED, TESTED

#33 [VYMCA-26] Multiple equipment reference in event
  js/gated-content/src/mixins/JsonApiCombineMixin.js
  js/gated-content/src/views/LiveStreamPage.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_equipment.yml
Labels: FiveJars, REVIEWED, TESTED

#35 updated date filter styles
  js/gated-content/src/scss/components/_video-listing.scss
Labels: IXM, REVIEWED, TESTED

#34 [VYMCA-25] Event series update
  openy_gated_content.module
Labels: NEEDS REVIEW, NEEDS TESTING

#36 Initial version of Daxko SSO for Gated Content
  js/gated-content/src/components/auth/DaxkoSSO.vue
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth/daxkosso.js
  js/gated-content/src/views/Login.vue
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/openy_gc_auth.provider.daxko_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_storage/openy_gc_storage.info.yml
Labels: IXM, NEEDS TESTING, REVIEWED

#39 [VYMCA-41] Fixes related to code review + small improvements
  README.md
  js/gated-content/.gitignore
  js/gated-content/package-lock.json
  js/gated-content/src/components/CategoryTeaser.vue
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LiveStreamTeaser.vue
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/components/VideoTeaser.vue
  js/gated-content/src/scss/components/_video-listing.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/Login.vue
  js/gated-content/src/views/VideoCategoriesListing.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_featured.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_title.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_category.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_description.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_duration.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_equipment.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_featured.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_instructor.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_level.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_media.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_category_media.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_description.yml
  patches/OEmbed_vimeo_private_videos.patch
Labels: FiveJars, NEEDS TESTING, REVIEWED

#31 Personify SSO adapter
  js/gated-content/src/components/LogoutLink.vue
  js/gated-content/src/components/auth/PersonifyAuth.vue
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/auth/personify.js
  js/gated-content/src/views/Login.vue
  modules/openy_gc_auth/modules/openy_gc_auth_personify/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_personify/config/install/openy_gc_auth.provider.personify.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.module
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
Labels: IXM, NEEDS REVIEW

#40 [VYMCA-43] Make 'Sign Out' a link
  js/gated-content/src/components/LiveStreamListing.vue
  js/gated-content/src/components/LogoutLink.vue
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/components/VideoListing.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#41 [VYMCA-17] CSV import data deletion
  .phpcs.xml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
  patches/migrate_tools_sync_option_for_drush8.patch
Labels: FiveJars, REVIEWED

#43 [VYMCA-49] Virtual Meeting content type
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_featured.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_ls_title.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_category.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_equipment.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_host_name.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_level.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_vm_link.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_vm_link.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_category.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_description.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_equipment.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_host_name.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_image.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_level.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_meeting_link.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_title.yml
  modules/openy_gc_storage/config/install/recurring_events.eventinstance_type.virtual_meeting.yml
  modules/openy_gc_storage/config/install/recurring_events.eventseries_type.virtual_meeting.yml
  openy_gated_content.module
  src/EventSubscriber/GatedContentSubscriber.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#44 [VYMCA-48] Blog page and listing
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/event/LiveStreamListing.vue
  js/gated-content/src/components/event/LiveStreamTeaser.vue
  js/gated-content/src/components/video/CategoryTeaser.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_blog-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/views/_blog-page.scss
  js/gated-content/src/views/BlogListingPage.vue
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoCategoriesListing.vue
  js/gated-content/src/views/VideoPage.vue
Labels: FiveJars, REVIEWED, TESTED

#47 [VYMCA-45] Add to Calendar link for Live Streams and Virtual Meetings
  config/install/openy_gated_content.settings.yml
  js/gated-content/package.json
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/event/AddToCalendar.vue
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/scss/components/_add-to-calendar.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/settings.js
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/openy_gc_auth.links.menu.yml
  modules/openy_gc_auth/openy_gc_auth.links.task.yml
  modules/openy_gc_auth/openy_gc_auth.routing.yml
  openy_gated_content.links.menu.yml
  openy_gated_content.module
  openy_gated_content.routing.yml
  src/Form/GCSettingsForm.php
  templates/paragraph--gated-content.html.twig
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING
