Repository fivejars/openy_gated_content, pull requests merged in 2021-11, with the labels that each got.

#409 [PRODDEV-470] Remove unused consts
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/SchedulePage.vue
Labels: REVIEWED, FiveJars

#397 [PRODDEV-365] ReClique SSO and others improvements
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
Labels: REVIEWED, NEEDS TESTING, FiveJars

#407 fix: Use Interface, not child Class in order to support other services
  modules/openy_gc_log/src/LogArchiver.php
Labels: bug, REVIEWED, NEEDS TESTING

#353 Support for timecode for vimeo and youtube videos.
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
Labels: REVIEWED, TESTED

#415 fix: Missed use class
  modules/openy_gc_log/src/LogArchiver.php
Labels: bug, REVIEWED

#412 [PRODDEV-463] Introduce automated welcome email for new users feature
  README.md
  composer.json
  config/install/openy_gated_content.welcome_email_settings.yml
  js/gated-content/dist/gated-content.css
  modules/openy_gc_auth/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/openy_gc_auth.links.task.yml
  modules/openy_gc_auth/openy_gc_auth.services.yml
  modules/openy_gc_auth/src/Controller/GCAuthController.php
  modules/openy_gc_auth/src/Event/GCUserLoginEvent.php
  modules/openy_gc_auth/src/Event/GCUserLogoutEvent.php
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_auth/src/GCUserAuthorizer.php
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/src/EventSubscriber/PersonalTrainingCanceledSubscriber.php
  openy_gated_content.install
  openy_gated_content.links.action.yml
  openy_gated_content.links.menu.yml
  openy_gated_content.links.task.yml
  openy_gated_content.module
  openy_gated_content.routing.yml
  openy_gated_content.services.yml
  src/EventSubscriber/GCUserLoginSubscriber.php
  src/EventSubscriber/GatedContentSubscriber.php
  src/Form/TestWelcomeEmail.php
  src/Form/WelcomeEmailSettingsForm.php
  src/GCUserService.php
Labels: REVIEWED, TESTED, FiveJars

#416 Update Shared Content Readme
  modules/openy_gc_shared_content/README.md
Labels: documentation, NEEDS REVIEW, IXM

#417 [PRODDEV-463] Documentation update
  modules/openy_gc_auth/README.md
Labels: documentation, NEEDS REVIEW
