Repository fivejars/openy_gated_content, pull requests merged in 2021-04, with the labels that each got.

#304 Fixed shared server checks
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
Labels: IXM, REVIEWED

#303 Fix config_dir in openy_gc_auth_custom_update_8009
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
Labels: REVIEWED

#306 Wrap the call to create a new Y-USA Provider user in a try...catch
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
Labels: NEEDS TESTING, REVIEWED

#305 Make "more" link more noticable
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/widgets/_listing-header.scss
Labels: REVIEWED, TESTED

#309 [YGS-305] Add possibility to process UNIX timestamps coming from Drup…
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/main.js
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/plugins/DayjsHelper.js
  js/gated-content/src/views/VideoPage.vue
Labels: REVIEWED, TESTED

#312 [PRODDEV-271] Make logs headers and content more human readable
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.api.php
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/src/LogArchiver.php
Labels: REVIEWED, TESTED

#314 Replaced hard-coded peers js server with custom that comes from admin
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/store/modules/personalTraining/webrtc.js
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.menu.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  openy_gated_content.module
Labels: IXM, NEEDS REVIEW

#310 Category filter modal (or "pop-up") overflows page
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/components/_modal.scss
Labels: REVIEWED, TESTED, bug

#321 [PRODDEV-277] Video Chat Chat component
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/ControlPanel.vue
  js/gated-content/src/components/personal-training/modal/Chat.vue
  js/gated-content/src/components/svg/SendIcon.vue
  js/gated-content/src/scss/components/personal-training/meeting/_control-panel.scss
  js/gated-content/src/scss/components/personal-training/modal/_chat.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/modules/personalTraining/chat.js
  js/gated-content/src/store/modules/personalTraining/modal.js
  modules/openy_gc_personal_training/assets/sound/new_message_sound.mp3
  modules/openy_gc_personal_training/openy_gc_personal_training.module
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#318 Correct the suggested input instruction on the Activity Log filtering controls
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.install
Labels: REVIEWED, TESTED

#322 [PRODDEV-277] Video Chat - use median instead of hardcoded breakpoint
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/components/personal-training/modal/_chat.scss
Labels: FiveJars, NEEDS REVIEW

#319 PRODDEV-274 + PRODDEV-275 + PRODDEV-276 + PRODDEV-279
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/assets/svg/cameraswitch_black_24dp.svg
  js/gated-content/src/components/personal-training/Meeting.vue
  js/gated-content/src/components/personal-training/meeting/ControlPanel.vue
  js/gated-content/src/components/personal-training/meeting/JoinMeeting.vue
  js/gated-content/src/components/personal-training/modal/Chat.vue
  js/gated-content/src/components/personal-training/modal/JoinOptions.vue
  js/gated-content/src/components/personal-training/modal/LeaveMeeting.vue
  js/gated-content/src/components/personal-training/modal/ViewOptions.vue
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/components/personal-training/_meeting.scss
  js/gated-content/src/scss/components/personal-training/meeting/_control-panel.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/scss/components/personal-training/modal/_leave-meeting.scss
  js/gated-content/src/scss/components/personal-training/modal/_view-options.scss
  js/gated-content/src/store/modules/personalTraining/chat.js
  js/gated-content/src/store/modules/personalTraining/controls.js
  js/gated-content/src/store/modules/personalTraining/modal.js
  js/gated-content/src/store/modules/personalTraining/webrtc.js
  js/gated-content/src/store/modules/personalTraining/webrtc/events.js
  js/gated-content/src/views/PersonalTrainingPage.vue
  modules/openy_gc_personal_training/js/simple-peer.js
  modules/openy_gc_personal_training/openy_gc_personal_training.libraries.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/src/Controller/PeerController.php
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Plugin/Block/VirtualYPersonalTrainingBlock.php
  modules/openy_gc_personal_training/templates/paragraph--personal-training.html.twig
  modules/openy_gc_personal_training/templates/personal_training.html.twig
Labels: IXM, REVIEWED, bug

#320 PRODDEV-87 + PRODDEV-88 + PRODDEV-92 + PRODDEV-144 + PRODDEV-93
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/event/ScheduleEventCard.vue
  js/gated-content/src/components/personal-training/PersonalTrainingListing.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/components/personal-training/modal/Chat.vue
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/mixins/FilterAndSortMixin.js
  js/gated-content/src/mixins/SeriesEventMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/modules/favorites.js
  js/gated-content/src/store/modules/personalTraining.js
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/PersonalTrainingPage.vue
  js/gated-content/src/views/SchedulePage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_log/src/Logger.php
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
  openy_gated_content.routing.yml
  src/Controller/EventsController.php
  src/Controller/FavoritesController.php
Labels: FiveJars, NEEDS TESTING, REVIEWED, bug

#324 [PRODDEV-277] Video Chat - fix message count display on mobile
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/ControlPanel.vue
  js/gated-content/src/scss/components/personal-training/meeting/_control-panel.scss
  js/gated-content/src/scss/components/personal-training/modal/_chat.scss
Labels: FiveJars, NEEDS REVIEW, TESTED

#325 Video calls connection testing
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/JoinMeeting.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/components/personal-training/modal/JoinOptions.vue
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/components/personal-training/_meeting.scss
  js/gated-content/src/scss/components/personal-training/meeting/_control-panel.scss
  js/gated-content/src/scss/components/personal-training/meeting/_join-meeting.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/store/modules/personalTraining/webrtc.js
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/src/Controller/PeerController.php
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
Labels: IXM

#326 [PRODDEV-144] Add "private" label to PTs' event cards on a schedules …
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/ScheduleEventCard.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/widgets/_private.scss
Labels: NEEDS REVIEW, NEEDS TESTING

#327 Updated description for the field
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
Labels: IXM, REVIEWED

#329 PRODDEV-294 Change title from Personal Training to 1on1
  modules/openy_gc_personal_training/README.md
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.action.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.menu.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.permissions.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingForm.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/Plugin/PersonalTrainingProvider/DefaultProvider.php
Labels: IXM, REVIEWED, TESTED
