Repository fivejars/openy_gated_content, pull requests merged in 2021-02, with the labels that each got.

#254 ReClique SSO Integration in openy_gc_auth_reclique_sso module
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/config/install/openy_gc_auth.provider.reclique_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.module
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Form/ContinueWithRecliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Plugin/GCIdentityProvider/RecliqueSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
Labels: IXM, NEEDS REVIEW, TESTED

#248 [VYMCA-127] Personal training entity
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.provider.default.yml
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/config/install/user.role.virtual_trainer.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.action.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.menu.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.links.task.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.permissions.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.services.yml
  modules/openy_gc_personal_training/personal_training.page.inc
  modules/openy_gc_personal_training/src/Annotation/PersonalTrainingProvider.php
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingInterface.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingViewsData.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingDeleteForm.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingForm.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingProviderEditForm.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingAccessControlHandler.php
  modules/openy_gc_personal_training/src/PersonalTrainingHtmlRouteProvider.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
  modules/openy_gc_personal_training/src/PersonalTrainingProviderInterface.php
  modules/openy_gc_personal_training/src/PersonalTrainingProviderManager.php
  modules/openy_gc_personal_training/src/PersonalTrainingProviderPluginBase.php
  modules/openy_gc_personal_training/src/Plugin/PersonalTrainingProvider/DefaultProvider.php
  modules/openy_gc_personal_training/templates/paragraph--personal-training.html.twig
  modules/openy_gc_personal_training/templates/personal_training.html.twig
Labels: FiveJars, NEEDS REVIEW

#244 User Activity Log - Tracking login times
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/main.js
  js/gated-content/src/plugins/log.js
  modules/openy_gc_log/config/install/openy_gc_log.settings.yml
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/js/datepicker.behaviors.js
  modules/openy_gc_log/js/logger.behaviors.js
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.links.menu.yml
  modules/openy_gc_log/openy_gc_log.links.task.yml
  modules/openy_gc_log/openy_gc_log.routing.yml
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/Controller/LogController.php
  modules/openy_gc_log/src/Entity/LogEntity.php
  modules/openy_gc_log/src/Entity/LogEntityInterface.php
  modules/openy_gc_log/src/EventSubscriber/GCLogUserLoginSubscriber.php
  modules/openy_gc_log/src/Field/PayloadFieldItemList.php
  modules/openy_gc_log/src/Form/LogSettingsForm.php
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/Logger.php
Labels: FiveJars, REVIEWED, TESTED, enhancement

#253 added a new option to config form of Custom Provider: now the "No valid One Time Link" message is configurable
  README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
  modules/openy_gc_log/js/.DS_Store
Labels: FiveJars, NEEDS TESTING

#218 [YGBWSVY-34] Fix user login issue
  openy_gated_content.module
  src/EditUserAccountAccessCheck.php
Labels: FiveJars, NEEDS TESTING, REVIEWED, bug

#259 [VYMCA-130] Fix pager in shared content
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--gc-video.html.twig
Labels: FiveJars, REVIEWED, TESTED

#260 [PRODDEV-179] Store references entities' info in the metadata field, …
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.post_update.php
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/Controller/LogController.php
  modules/openy_gc_log/src/Entity/LogEntity.php
  modules/openy_gc_log/src/Field/PayloadFieldItemList.php
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/Logger.php
Labels: FiveJars, REVIEWED, TESTED

#257 Vimeo private url fix
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
Labels: REVIEWED, TESTED

#261 Migrate Virtual Y small banner image
  openy_gated_content.post_update.php
Labels: NEEDS TESTING, REVIEWED

#258 [PRODDEV-111] Request verification only once per browser
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/config/install/openy_gc_auth.provider.reclique_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.module
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Form/ContinueWithRecliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Plugin/GCIdentityProvider/RecliqueSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Controller/UserController.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/src/GCVerificationTrait.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--gc-video.html.twig
  openy_gated_content.module
  openy_gated_content.post_update.php
  src/EditUserAccountAccessCheck.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING, TESTED

#266 Align video footer
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/views/_video-page.scss
Labels: IXM, NEEDS REVIEW, NEEDS TESTING

#263 1.2.3 Minor pre release fixes.
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/openy_gc_auth_daxko_barcode.install
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Plugin/GCIdentityProvider/DaxkoBarcode.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
Labels: IXM, NEEDS REVIEW

#264 [VYMCA-115] Admin accounts for CSV import
  modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/process/SkipRowIfEmailExcluded.php
Labels: FiveJars, NEEDS TESTING, REVIEWED, TESTED

#272 Enable pagination for video listing on category page when video filter is selected
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/CategoryPage.vue
Labels: IXM, NEEDS TESTING, REVIEWED

#271 Update PersonifyAuthController.php to not grant access to Cancelled/Expired members
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
Labels: REVIEWED, TESTED, bug

#273 [PRODDEV-239] Fix field_vy_permission widget condition for non-VY content types
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
Labels: FiveJars, REVIEWED, TESTED, bug

#270 [VYMCA-134] Publishing Series Workflow Should Be Reflected in Instances
  composer.json
Labels: FiveJars, REVIEWED, TESTED

#276 Enable pagination for video listing on category page when video filter is selected (master)
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/CategoryPage.vue
Labels: IXM, NEEDS TESTING, REVIEWED, TESTED

#278 [hotfix] Use tested recurring_events version
  composer.json
Labels: FiveJars, NEEDS REVIEW, bug

#277 Duration bug on livestream teaser and change date library to dayjs
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/main.js
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/views/VideoPage.vue
Labels: IXM, NEEDS TESTING, REVIEWED

#280 If somebody has no plan to upgrade a module - we should not block
  composer.json
Labels: NEEDS REVIEW
