Repository fivejars/openy_gated_content, pull requests merged in 2021-09, with the labels that each got.

#379 [PRODDEV-423] Update dependencies and patches.
  composer.json
Labels: REVIEWED, NEEDS TESTING, FiveJars

#380 [PRODDEV-437] Fix teasers' fields shifts
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/Teaser.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/category/CategoryTeaser.vue
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/components/_event-teaser.scss
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/widgets/_teaser.scss
Labels: REVIEWED, TESTED, FiveJars

#378 [PRODDEV-411] Install and update definitions for the fields needing t…
  modules/openy_gc_shared_content/openy_gc_shared_content.module
  openy_gated_content.install
  openy_gated_content.module
  src/Entity/VyFavoriteItem.php
  src/VyFavoriteItemInterface.php
Labels: REVIEWED, NEEDS TESTING, FiveJars

#382 Added description
  modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php
Labels: REVIEWED, TESTED, IXM

#383 [PRODDEV-432] Remove migrate_tools version dependency
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/MigrateBatchExecutable.php
Labels: REVIEWED, FiveJars

#381 [PRODDEV-410] Avocado - Blocked Sessions
  SMOKE_TESTS.md
  composer.json
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/SSOClient.php
  openy_gated_content.info.yml
Labels: REVIEWED, TESTED, IXM

#377 Update of jsonapi_image_styles
  composer.json
Labels: REVIEWED, TESTED, FiveJars, IXM

#385 [PRODDEV-389] Override bootstrap added outline for the bootstrap prio…
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/components/_add-to-calendar.scss
Labels: REVIEWED, TESTED, FiveJars

#386 [PRODDEV-431] Refactor listings to have the same behavior everywhere.…
  SMOKE_TESTS.md
  composer.json
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/category/CategoriesListing.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/personal-training/PersonalTrainingListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/mixins/ListingMixin.js
  js/gated-content/src/views/CategoriesListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/SSOClient.php
  openy_gated_content.info.yml
Labels: REVIEWED, TESTED, FiveJars

#387 [PRODDEV-415] Instructor taxonomy BE, upgrade path, demo content
  modules/openy_gc_demo/assets/images/Emanuel-D.jpg
  modules/openy_gc_demo/assets/images/Molly-R.jpg
  modules/openy_gc_demo/assets/images/Olivia-P.jpg
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_file.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_instructor.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_image.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_live_stream.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_reccuring_event_virtual_meeting.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.post_update.php
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.taxonomy_term.gc_instructor.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.virtual_meeting.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.teaser.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.taxonomy_term.gc_instructor.default.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_instructor.field_gc_instructor_categories.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_instructor.field_gc_instructor_difficulty.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_instructor.field_gc_instructor_photo.yml
  modules/openy_gc_storage/config/install/field.storage.eventinstance.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.storage.eventseries.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_instructor_reference.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_instructor_categories.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_instructor_difficulty.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_instructor_photo.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_instructor_reference.yml
  modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_instructor_reference.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_instructor.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_instructor.yml
  modules/openy_gc_storage/openy_gc_storage.install
  modules/openy_gc_storage/openy_gc_storage.post_update.php
  openy_gated_content.links.menu.yml
Labels: REVIEWED, TESTED, FiveJars

#388 [PRODDEV-416] Build Duration filter with Taxonomy
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/TopMenu.vue
  js/gated-content/src/components/duration/DurationTeaser.vue
  js/gated-content/src/components/duration/DurationsListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_duration-teaser.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/modules/favorites.js
  js/gated-content/src/views/DurationPage.vue
  js/gated-content/src/views/DurationsListingPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/HomeLegacy.vue
  js/gated-content/src/views/HomeWrapper.vue
  modules/openy_gc_personal_training/README.md
  modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_form_display.taxonomy_term.gc_duration.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.default.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.teaser.yml
  modules/openy_gc_storage/config/install/core.entity_view_display.taxonomy_term.gc_duration.default.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_duration_reference.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_duration.field_gc_duration_max.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_duration.field_gc_duration_media.yml
  modules/openy_gc_storage/config/install/field.field.taxonomy_term.gc_duration.field_gc_duration_min.yml
  modules/openy_gc_storage/config/install/field.storage.node.field_gc_duration_reference.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_duration_max.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_duration_media.yml
  modules/openy_gc_storage/config/install/field.storage.taxonomy_term.field_gc_duration_min.yml
  modules/openy_gc_storage/config/install/language.content_settings.taxonomy_term.gc_duration.yml
  modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_duration.yml
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.info.yml
  openy_gated_content.links.menu.yml
  src/Controller/FavoritesController.php
  src/Form/GCSettingsForm.php
Labels: NEEDS REVIEW, NEEDS TESTING, IXM

#392 [PRODDEV-450] Fix the error on a fields definitions' update
  openy_gated_content.install
Labels: REVIEWED, NEEDS TESTING, FiveJars

#390 [PRODDEV-439] Add hook_update to update existed data and add duration reference
  modules/openy_gc_storage/openy_gc_storage.post_update.php
  openy_gated_content.links.menu.yml
  openy_gated_content.module
  openy_gated_content.routing.yml
  src/Form/RebuildDurationsForm.php
Labels: NEEDS REVIEW, IXM
