Repository fivejars/openy_gated_content, pull requests merged in 2021-07, with the labels that each got.

#355 [PRODDEV-362] Implement autoplay for the videos, controlled per compo…
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#354 FE fixes for PRODDEV-349
  README.md
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/AudioIndicator.vue
  js/gated-content/src/scss/components/_svg-icon.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
  js/gated-content/src/store/modules/personalTraining/webrtc/mediaStream.js
  modules/openy_gc_auth/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/README.md
  modules/openy_gc_personal_training/README.md
  modules/openy_gc_personal_training/assets/vy_14_remote_link.png
  modules/openy_gc_personal_training/assets/vy_14_virtual_meeting.png
  openy_gated_content.info.yml
Labels: IXM, NEEDS REVIEW, TESTED

#352 [PRODDEV-338] Recurring Appointments
  composer.json
  modules/openy_gc_personal_training/config/install/core.entity_form_display.personal_training.personal_training.default.yml
  modules/openy_gc_personal_training/config/install/core.entity_form_display.personal_training.training_series.default.yml
  modules/openy_gc_personal_training/config/install/field.field.personal_training.personal_training.field_parent.yml
  modules/openy_gc_personal_training/config/install/field.field.personal_training.training_series.field_exclusions.yml
  modules/openy_gc_personal_training/config/install/field.field.personal_training.training_series.field_schedule.yml
  modules/openy_gc_personal_training/config/install/field.storage.personal_training.field_exclusions.yml
  modules/openy_gc_personal_training/config/install/field.storage.personal_training.field_parent.yml
  modules/openy_gc_personal_training/config/install/field.storage.personal_training.field_schedule.yml
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.type.personal_training.yml
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.type.training_series.yml
  modules/openy_gc_personal_training/config/install/views.view.personal_trainings.yml
  modules/openy_gc_personal_training/config/schema/personal_training_type.schema.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.links.action.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.post_update.php
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.services.yml
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingType.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManager.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManagerInterface.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesOperations.php
  modules/openy_gc_personal_training/templates/vy-training-series-date-recur-modular-alpha-widget.html.twig
  openy_gated_content.module
  src/VyFavoriteItemsManager.php
Labels: FiveJars, REVIEWED, TESTED

#356 Proddev 349
  README.md
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/AudioIndicator.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/components/personal-training/meeting/VideoIndicator.vue
  js/gated-content/src/components/personal-training/modal/JoinOptions.vue
  js/gated-content/src/scss/_variables.scss
  js/gated-content/src/scss/components/_svg-icon.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/store/modules/personalTraining/webrtc/mediaStream.js
  modules/openy_gc_auth/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/README.md
  modules/openy_gc_personal_training/README.md
  modules/openy_gc_personal_training/assets/vy_14_remote_link.png
  modules/openy_gc_personal_training/assets/vy_14_virtual_meeting.png
  openy_gated_content.info.yml
Labels: NEEDS REVIEW, NEEDS TESTING

#357 [PRODDEV-362] Make log event sent immediately after the video paused
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
Labels: FiveJars, REVIEWED, TESTED

#360 Minor fix: argument type error fix
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/ScheduleEventCard.vue
Labels: FiveJars, NEEDS TESTING, REVIEWED, bug

#361 [PRODDEV-370][PRODDEV-371] Nested categories
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/category/CategoriesListing.vue
  js/gated-content/src/components/category/CategoryLinks.vue
  js/gated-content/src/components/category/CategoryTeaser.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/mixins/FilterAndSortMixin.js
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/layout/four-columns.scss
  js/gated-content/src/scss/layout/one-columns.scss
  js/gated-content/src/scss/layout/three-columns.scss
  js/gated-content/src/scss/layout/two-columns.scss
  js/gated-content/src/scss/views/_blog-page.scss
  js/gated-content/src/scss/views/_category-page.scss
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/categories.js
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/BlogsListingPage.vue
  js/gated-content/src/views/CategoriesListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VideosListingPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  src/Controller/CategoriesController.php
Labels: NEEDS REVIEW, NEEDS TESTING, TESTED

#363 PRODDEV-372 Create admin error message for 2nd level of Categories
  openy_gated_content.info.yml
  openy_gated_content.module
Labels: IXM, NEEDS REVIEW

#365 PRODDEV-395, PRODDEV-394 Assign form-control css class to text input …
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/modal/UserName.vue
Labels: IXM, REVIEWED, TESTED

#358 [PRODDEV-301] VY chat: Allow users/staff to enter name
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/JoinMeeting.vue
  js/gated-content/src/components/personal-training/modal/Chat.vue
  js/gated-content/src/components/personal-training/modal/UserName.vue
  js/gated-content/src/scss/utilities/_colors.scss
  js/gated-content/src/scss/widgets/button.scss
  js/gated-content/src/store/modules/personalTraining.js
  js/gated-content/src/store/modules/personalTraining/modal.js
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/src/Controller/UserController.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
Labels: FiveJars, REVIEWED, TESTED

#362 [PRODDEV-355] Cancel Session - Notifications
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingItemsOperations.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING

#366 [PRODDEV-355], [PRODDEV-378], [PRODDEV-380]
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/ScheduleEventCard.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/widgets/_canceled.scss
  js/gated-content/src/scss/widgets/_teaser.scss
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/config/install/user.role.virtual_trainer.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.permissions.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.services.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.workflow_groups.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.workflows.yml
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingInterface.php
  modules/openy_gc_personal_training/src/EventSubscriber/PersonalTrainingCanceledSubscriber.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingItemsOperations.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManager.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManagerInterface.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesOperations.php
  openy_gated_content.module
Labels: IXM, NEEDS REVIEW, REVIEWED, TESTED
