Repository fivejars/openy_gated_content, pull requests merged in 2021-06, with the labels that each got.

#347 [PRODDEV-345] Hide 1px green border coming from some devices' cameras
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
Labels: FiveJars, REVIEWED, TESTED

#344 Fixed menu link for admin views for events and events instances
  modules/openy_gc_storage/config/install/views.view.virtual_y_event_series.yml
  modules/openy_gc_storage/config/install/views.view.virtual_y_events.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: IXM, REVIEWED, TESTED

#350 [PRODDEV-189] Add carnation_banner image style and use it for Blog an…
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/Teaser.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/category/CategoryTeaser.vue
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/mixins/ImageStyleMixin.js
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_storage/openy_gc_storage.install
Labels: FiveJars, NEEDS TESTING, REVIEWED

#349 [PRODDEV-347] Use simple_recaptcha module rather than the reCaptcha for the validation
  composer.json
  js/gated-content/dist/gated-content.css
  js/gated-content/src/scss/views/_login.scss
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/openy_gc_auth_daxko_barcode.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/openy_gc_auth_reclique.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Form/VirtualYReCliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Plugin/GCIdentityProvider/ReClique.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/openy_gc_auth_yusa.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
  modules/openy_gc_auth/openy_gc_auth.install
  openy_gated_content.info.yml
  openy_gated_content.libraries.yml
Labels: FiveJars, REVIEWED, TESTED
