Repository fivejars/openy_gated_content, pull requests merged in 2021-01, with the labels that each got.

#226 [VYMCA-120] Fix growByHeight issue and Vimeo Events issues
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  js/gated-content/src/components/event/AddToCalendar.vue
  js/gated-content/src/scss/views/_video-page.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: FiveJars, REVIEWED, TESTED

#228 Updated zoom documents.
  modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_vm_link.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: REVIEWED, TESTED

#231 [VYMCA-117] Improve favorites performance
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/components/AddToFavorite.vue
  js/gated-content/src/store/modules/favorites.js
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/SchedulePage.vue
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/YUSAClientService.php
  openy_gated_content.services.yml
  src/Controller/FavoritesController.php
Labels: FiveJars, REVIEWED, TESTED

#234 [VYMCA-125] Delete hard dependency to migrate_tools:5.0
  composer.json
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/MigrateBatchExecutable.php
Labels: FiveJars, REVIEWED, TESTED

#230 Association number field validation applied
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
Labels: NEEDS TESTING, REVIEWED

#235 headline button font sizes, media field description note and favorite-outlined svg
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/dist/img/favorites-outlined.4df06a61.svg
  js/gated-content/dist/img/favorites-solid.b97dd183.svg
  js/gated-content/src/scss/components/_favorites.scss
  js/gated-content/src/scss/components/_paragraph-headline.scss
  js/gated-content/src/scss/utilities/_fonts.scss
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_media.yml
  modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_media.yml
  modules/openy_gc_storage/openy_gc_storage.install
Labels: IXM, REVIEWED, TESTED

#233 [VYMCA-126] Fix access checks and returned categories array
  src/Controller/CategoriesController.php
  src/GCUserService.php
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
  src/SegmentContentAccessCheck.php
Labels: FiveJars, REVIEWED, TESTED, bug

#232 [VYMCA-121] Demo content for blogs
  modules/openy_gc_demo/assets/images/Blaisdell-Group-Fitness-barbells-0057.jpg
  modules/openy_gc_demo/assets/images/Blaisdell-Group-Fitness-bosu-0062.jpg
  modules/openy_gc_demo/assets/images/Dayton-Y-Harmony-Yoga-Group-Exercise-7971.jpg
  modules/openy_gc_demo/assets/images/Family-Group-Outdoor-father-son-sledding.jpg
  modules/openy_gc_demo/assets/images/George-Wellness-Center-Meditation-1109.jpg
  modules/openy_gc_demo/assets/images/Lino-Lakes-Group-Fitness-Mat-Pilates0147.jpg
  modules/openy_gc_demo/assets/images/Lino-Lakes-Group-Fitness-Zumba0155.jpg
  modules/openy_gc_demo/assets/images/child-winter-153490472.jpg
  modules/openy_gc_demo/assets/images/foreverwell-group-0005.jpg
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_file.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_category.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_media_image.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
Labels: FiveJars, REVIEWED, TESTED

#236 filter modal buttons uppercase and instructor value check
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/scss/components/_adjust-modal.scss
  js/gated-content/src/views/FavoritesPage.vue
Labels: IXM, REVIEWED, TESTED

#237 [VYMCA-124] Favorite's page behavior fix
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/FilterAndSortMixin.js
  js/gated-content/src/views/CategoriesListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_gc_category.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
Labels: FiveJars, REVIEWED, TESTED

#242 Daxko install fix
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/install/openy_gc_auth.provider.daxko_sso.yml
  modules/openy_gc_log/src/LogArchiver.php
Labels: NEEDS REVIEW

#239 Add null checks for entity on log archiver.
  modules/openy_gc_log/src/LogArchiver.php
Labels: REVIEWED, TESTED, bug

#238 Use range instead of limit for autologout cron
  modules/openy_gc_autologout/openy_gc_autologout.module
Labels: NEEDS TESTING, REVIEWED

#241 Pt mvp
  modules/openy_gc_personal_training/js/simple-peer.js
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.libraries.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/src/Plugin/Block/VirtualYPersonalTrainingBlock.php
  modules/openy_gc_personal_training/templates/paragraph--personal-training.html.twig
Labels: DO NOT MERGE

#240 [PRODDEV-160][PRODDEV-161] Fix the top menu placement and the overflo…
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/components/_top-menu.scss
  js/gated-content/src/scss/views/_video-page.scss
Labels: FiveJars, REVIEWED, TESTED, bug

#246 Class Levels not showing on current designs
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/assets/svg/difficulty-icon-grey.svg
  js/gated-content/src/assets/svg/difficulty-icon-white.svg
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/scss/components/_event-teaser.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: IXM, NEEDS REVIEW, TESTED

#243 Styles for top menu with alerts
  assets/js/alerts.behaviors.js
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/main.js
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/theme_overrides.scss
  openy_gated_content.libraries.yml
Labels: IXM, NEEDS REVIEW, TESTED

#250 Use the LoggerChannelFactoryInterface instead of exact LoggerChannelFactory in the DaxkoBarcodeController
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
Labels: NEEDS TESTING, REVIEWED

#252 Update README.md - server requirements
  README.md
Labels: REVIEWED, documentation

#249 [PRODDEV-188] Fix Activity Log export if user is null
  modules/openy_gc_log/src/LogArchiver.php
Labels: NEEDS REVIEW, NEEDS TESTING
