Repository fivejars/openy_gated_content, pull requests merged in 2021-05, with the labels that each got.

#331 [PRODDEV-303] Add and configure mobile background image for the PT
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/img/background-m.1759a037.png
  js/gated-content/src/assets/img/background-m.png
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/components/personal-training/meeting/_join-meeting.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
Labels: NEEDS REVIEW, REVIEWED, TESTED

#328 Video calls connection testing
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/personal-training/meeting/JoinMeeting.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/scss/components/personal-training/meeting/_join-meeting.scss
  js/gated-content/src/scss/components/personal-training/meeting/_meeting-player.scss
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/store/index.js
  js/gated-content/src/store/modules/debugLog.js
  js/gated-content/src/store/modules/personalTraining.js
  js/gated-content/src/store/modules/personalTraining/chat.js
  js/gated-content/src/store/modules/personalTraining/controls.js
  js/gated-content/src/store/modules/personalTraining/modal.js
  js/gated-content/src/store/modules/personalTraining/webrtc.js
  js/gated-content/src/store/modules/personalTraining/webrtc/events.js
  js/gated-content/src/store/modules/personalTraining/webrtc/mediaStream.js
  js/gated-content/src/store/modules/personalTraining/webrtc/peerConnection.js
  js/gated-content/src/store/modules/personalTraining/webrtc/signalingServer.js
  js/gated-content/src/views/PersonalTrainingPage.vue
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.libraries.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
Labels: IXM

#330 Cloning issue with Event series and Event instances.
  openy_gated_content.module
Labels: TESTED

#332 [PRODDEV-326] Changes in media queries and openy_carnation theme spec…
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/scss/_mixins.scss
  js/gated-content/src/scss/theme_overrides.scss
Labels: REVIEWED, TESTED

#333 Mic and Camera device selection modal window for Personal Training
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/assets/svg/settings_black_24dp.svg
  js/gated-content/src/components/personal-training/meeting/JoinMeeting.vue
  js/gated-content/src/components/personal-training/modal/JoinOptions.vue
  js/gated-content/src/components/personal-training/modal/deviceManager.vue
  js/gated-content/src/scss/components/personal-training/modal/_device-manager.scss
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/store/modules/personalTraining.js
  js/gated-content/src/store/modules/personalTraining/modal.js
  js/gated-content/src/store/modules/personalTraining/webrtc.js
  js/gated-content/src/store/modules/personalTraining/webrtc/deviceManager.js
  js/gated-content/src/store/modules/personalTraining/webrtc/events.js
  js/gated-content/src/store/modules/personalTraining/webrtc/mediaStream.js
  js/gated-content/src/store/modules/personalTraining/webrtc/peerConnection.js
  js/gated-content/src/store/modules/personalTraining/webrtc/signalingServer.js
  js/gated-content/src/views/PersonalTrainingPage.vue
Labels: IXM, REVIEWED, TESTED

#336 Fix duplicated function name
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_personal_training/openy_gc_personal_training.install
Labels: FiveJars, REVIEWED, bug

#338 [PRODDEV-285] Add images back into VY as optional field
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/Teaser.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/blog/BlogTeaser.vue
  js/gated-content/src/components/category/CategoryTeaser.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/personal-training/PersonalTrainingListing.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/mixins/ListingMixin.js
  js/gated-content/src/router/index.js
  js/gated-content/src/scss/components/_blog-teaser.scss
  js/gated-content/src/scss/components/_category-teaser.scss
  js/gated-content/src/scss/components/_event-teaser.scss
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/components/_video-teaser.scss
  js/gated-content/src/scss/widgets/_teaser.scss
  js/gated-content/src/views/BlogPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VirtualMeetingListingPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_image.yml
  modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_ls_image.yml
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: FiveJars, REVIEWED, TESTED

#341 [PRODDEV-266] Fix menu items migration
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_menu_link_main.yml
Labels: FiveJars, NEEDS TESTING, REVIEWED

#339 [PRODDEV-269] Use the tempstore.private instead of the deprecated use…
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/Form/VirtualYReCliqueLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/openy_gc_auth_reclique_sso.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
Labels: FiveJars, REVIEWED, TESTED

#342 [PRODDEV-350] Add cache context for anonymous users if we have x-shared-referer header
  modules/openy_gc_shared_content_server/src/Controller/DownloadsIncrementController.php
  src/EventSubscriber/GatedContentSubscriber.php
Labels: FiveJars, NEEDS REVIEW, NEEDS TESTING, bug

#343 [PRODDEV-344] Shared content improvements
  modules/openy_gc_shared_content/openy_gc_shared_content.module
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content/templates/openy-gc-shared-content--vy-blog-post.html.twig
  modules/openy_gc_shared_content_server/src/Plugin/rest/resource/SharedSourceCreate.php
Labels: FiveJars, REVIEWED, TESTED

#345 Made Shared content vitual y video as default tab.
  modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml
Labels: TESTED

#346 [IN-84] Fix AcquiaDrupalStrict and drupal-check reports
  README.md
  js/README.md
  js/gated-content.md
  modules/README.md
  modules/openy_gc_auth/modules/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUserInterface.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/process/SkipRowIfEmailExcluded.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthConfirm.php
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
  modules/openy_gc_auth/modules/openy_gc_auth_example/src/Form/VirtualYExampleLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/README.md
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/EventSubscriber/PersonifyUserLogoutSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/src/Controller/GCAuthController.php
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/GCAuthManager.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_auth/src/Plugin/Block/VirtualYLoginBlock.php
  modules/openy_gc_autologout/README.md
  modules/openy_gc_autologout/openy_gc_autologout.module
  modules/openy_gc_demo/src/Plugin/migrate/process/FlyParagraph.php
  modules/openy_gc_log/src/Controller/LogController.php
  modules/openy_gc_log/src/Entity/LogEntity.php
  modules/openy_gc_log/src/LogEntityAccessControlHandler.php
  modules/openy_gc_personal_training/src/Controller/PeerController.php
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/PersonalTrainingAccessControlHandler.php
  modules/openy_gc_personal_training/src/PersonalTrainingListBuilder.php
  modules/openy_gc_personal_training/src/PersonalTrainingProviderInterface.php
  modules/openy_gc_personal_training/src/Plugin/PersonalTrainingProvider/DefaultProvider.php
  modules/openy_gc_shared_content/src/Entity/SharedContentSourceServer.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php
  modules/openy_gc_shared_content_server/src/SharedContentSourceAccessControlHandler.php
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
  src/Plugin/video_embed_field/Provider/VimeoEvent.php
Labels: FiveJars, NEEDS REVIEW, enhancement
