Repository fivejars/openy_gated_content, pull requests merged in 2021-12, with the labels that each got.

#420 [PRODDEV-488] added duration_reference for video migration
  modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml
Labels: REVIEWED, TESTED

#421 PRODDEV-485 1on1 Readme
  modules/openy_gc_personal_training/README.md
Labels: NEEDS WORK

#418 [PRODDEV-484] Add patch to resolve indexing error
  composer.json
Labels: TESTED

#402 Openy 163 Resolved Virtual Y: With Y-USA Provider, members with same first name and last name cannot authenticate with barcode
  modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
Labels: REVIEWED, TESTED

#423 [PRODDEV-479] [PRODDEV-480] Flag new shared content
  assets/css/admin_ui_styles.css
  composer.json
  modules/openy_gc_shared_content/src/Controller/PreviewController.php
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/Form/SharedContentPreviewForm.php
  modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
Labels: TESTED

#425 [PRODDEV-329] Allow site admins to remove menu items
  config/install/openy_gated_content.settings.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/TopMenu.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: TESTED

#419 Proddev 340
  modules/openy_gc_personal_training/config/install/views.view.personal_trainings.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingType.php
Labels: TESTED
