Repository fivejars/openy_gated_content, pull requests merged in 2021-03, with the labels that each got.

#284 Master to 1.3
  composer.json
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/components/event/EventTeaser.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/filters/index.js
  js/gated-content/src/main.js
  js/gated-content/src/mixins/EventMixin.js
  js/gated-content/src/views/VideoPage.vue
  src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
Labels: NEEDS REVIEW

#285 [PRODDEV-243] Add missed dependencies
  modules/openy_gc_demo/openy_gc_demo.info.yml
Labels: FiveJars, NEEDS REVIEW

#279 Update PersonifyAuthController.php to not grant access to Cancelled/Expired members (master)
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/EventSubscriber/PersonifyUserLogoutSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/LogoutClient.php
Labels: NEEDS REVIEW, NEEDS TESTING

#287 Fixed bug with not working shared content fetcher
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_blog.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_video.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_category.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_equipment.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_level.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_blog_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video_image.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_blog.yml
  modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_video.yml
  modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php
  src/SegmentContentAccessCheck.php
Labels: IXM, REVIEWED

#286 [PRODDEV-187] Group activity logs by day for user
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.api.php
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_log/openy_gc_log.views.inc
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/Plugin/views/field/GCLogDayField.php
  modules/openy_gc_log/src/Plugin/views/field/GCLogDurationField.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#267 Config and view updates for empty block settings.
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/LiveStreamListingPage.vue
  js/gated-content/src/views/LiveStreamPage.vue
  js/gated-content/src/views/VirtualMeetingListingPage.vue
  js/gated-content/src/views/VirtualMeetingPage.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: NEEDS TESTING, REVIEWED

#288 [PRODDEV-229] Fix referer header for shared content
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#274 [PRODDEV-231] VY Dashboard/Home Reorder Content Feature
  assets/css/admin_ui_styles.css
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/SettingsMixin.js
  js/gated-content/src/scss/theme_overrides.scss
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  openy_gated_content.install
  openy_gated_content.libraries.yml
  openy_gated_content.module
  src/Form/GCSettingsForm.php
Labels: FiveJars, REVIEWED, TESTED, enhancement

#229 [VYMCA-116] Provide search functionality
  composer.json
  modules/openy_gc_search/README.md
  modules/openy_gc_search/openy_gc_search.info.yml
  modules/openy_gc_search/openy_gc_search.install
  modules/openy_gc_search/openy_gc_search.module
Labels: FiveJars, REVIEWED, TESTED

#283 ReClique: Default role to Virtual YMCA if no mapping (to master)
  modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/EventSubscriber/GCAuthReCliqueUserLoginSubscriber.php
Labels: NEEDS TESTING, REVIEWED

#289 [PRODDEV-219] Implement redirect after login
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/package.json
  js/gated-content/src/main.js
  modules/openy_gc_auth/js/auth.behaviors.js
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/Plugin/GCIdentityProvider/RecliqueSSO.php
  modules/openy_gc_auth/openy_gc_auth.libraries.yml
  modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
  modules/openy_gc_auth/src/Plugin/Block/VirtualYLoginBlock.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#290 [PRODDEV-240] Disable double patching of the search_api, add processo…
  composer.json
  modules/openy_gc_search/openy_gc_search.install
Labels: FiveJars, REVIEWED, TESTED

#292 [PRODDEV-193] Give access for Virtual Y Instructor to view any training
  modules/openy_gc_personal_training/config/install/user.role.virtual_trainer.yml
  modules/openy_gc_personal_training/src/Plugin/PersonalTrainingProvider/DefaultProvider.php
Labels: FiveJars, REVIEWED, TESTED

#294 Updated recurring events views.
  modules/openy_gc_storage/config/install/views.view.virtual_y_event_series.yml
  modules/openy_gc_storage/config/install/views.view.virtual_y_events.yml
  modules/openy_gc_storage/openy_gc_storage.info.yml
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.links.menu.yml
Labels: IXM, REVIEWED, TESTED

#298 Proddev 261
  config/install/openy_gated_content.settings.yml
  config/schema/openy_gated_content.schema.yml
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/mixins/FilterAndSortMixin.js
  js/gated-content/src/views/BlogsListingPage.vue
  js/gated-content/src/views/CategoriesListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/FavoritesPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/VideosListingPage.vue
  openy_gated_content.install
  src/Form/GCSettingsForm.php
Labels: FiveJars, NEEDS TESTING, REVIEWED

#300 [PRODDEV-194] Doc about Personal training structure
  modules/openy_gc_personal_training/README.md
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
Labels: FiveJars, NEEDS REVIEW

#301 Fix duplicate logs in export files
  modules/openy_gc_log/openy_gc_log.module
  modules/openy_gc_log/src/LogArchiver.php
Labels: IXM, TESTED

#262 Added youtube player attributes handler
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  modules/openy_gc_log/src/LogArchiver.php
Labels: TESTED

#302 13 to master.
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/MediaPlayer.vue
  modules/openy_gc_log/openy_gc_log.module
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_shared_content/src/Plugin/Action/ShareToVirtualYBase.php
  modules/openy_gc_shared_content/src/Plugin/Action/UnshareFromVirtualYBase.php
Labels: REVIEWED
