Repository fivejars/openy_gated_content, pull requests merged in 2021-08, with the labels that each got.

#369 Session notifications
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/components/event/ScheduleEventCard.vue
  js/gated-content/src/components/personal-training/PersonalTrainingTeaser.vue
  js/gated-content/src/scss/components/_personal-training-listing.scss
  js/gated-content/src/scss/global.scss
  js/gated-content/src/scss/widgets/_canceled.scss
  js/gated-content/src/scss/widgets/_teaser.scss
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php
  modules/openy_gc_auth/src/GCIdentityProviderInterface.php
  modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
  modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
  modules/openy_gc_personal_training/config/install/user.role.virtual_trainer.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.permissions.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.services.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.workflow_groups.yml
  modules/openy_gc_personal_training/openy_gc_personal_training.workflows.yml
  modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
  modules/openy_gc_personal_training/src/Entity/PersonalTrainingInterface.php
  modules/openy_gc_personal_training/src/EventSubscriber/PersonalTrainingCanceledSubscriber.php
  modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManager.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManagerInterface.php
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesOperations.php
  openy_gated_content.module
Labels: REVIEWED, TESTED

#370 [PRODDEV-408] Display video preview on a small screens, show actual s…
  js/gated-content/dist/gated-content.css
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/GatedContent.vue
  js/gated-content/src/components/TopMenu.vue
  js/gated-content/src/components/blog/BlogListing.vue
  js/gated-content/src/components/category/CategoriesListing.vue
  js/gated-content/src/components/event/EventListing.vue
  js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
  js/gated-content/src/components/personal-training/modal/Chat.vue
  js/gated-content/src/components/personal-training/modal/JoinOptions.vue
  js/gated-content/src/components/personal-training/modal/LeaveMeeting.vue
  js/gated-content/src/components/personal-training/modal/UserName.vue
  js/gated-content/src/components/personal-training/modal/ViewOptions.vue
  js/gated-content/src/components/personal-training/modal/deviceManager.vue
  js/gated-content/src/components/video/VideoListing.vue
  js/gated-content/src/components/video/VideoTeaser.vue
  js/gated-content/src/scss/components/personal-training/modal/_join-options.scss
  js/gated-content/src/store/modules/personalTraining.js
  js/gated-content/src/views/BlogsListingPage.vue
  js/gated-content/src/views/CategoryPage.vue
  js/gated-content/src/views/Home.vue
  js/gated-content/src/views/VideoPage.vue
  js/gated-content/src/views/VideosListingPage.vue
Labels: REVIEWED, TESTED, FiveJars

#368 Readme for Cancel Sessions notifications
  modules/openy_gc_personal_training/README.md
Labels: documentation

#359 Build Avocado SSO
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/config/install/openy_gc_auth.provider.avocado_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/openy_gc_auth_avocado_sso.info.yml
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/openy_gc_auth_avocado_sso.module
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/openy_gc_auth_avocado_sso.routing.yml
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/openy_gc_auth_avocado_sso.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Controller/SSOController.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Form/AvocadoLoginForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Form/TryAgainForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/Plugin/GCIdentityProvider/AvocadoSSO.php
  modules/openy_gc_auth/modules/openy_gc_auth_avocado_sso/src/SSOClient.php
Labels: DO NOT MERGE, NEEDS WORK, IXM

#364 Grammar updates and STUN server info
  modules/openy_gc_personal_training/README.md
Labels: documentation

#375 Fix recurring events Event Series View
  composer.json
Labels: bug, REVIEWED, NEEDS TESTING

#374 [PRODDEV-413] Set the event time zone to UTC
  src/Controller/EventsController.php
Labels: REVIEWED, TESTED
