Repository fivejars/openy_gated_content, pull requests merged in 2022-02, with the labels that each got.

#446 CS + Deprecation fixes
  modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
  modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
  modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.install
  modules/openy_gc_log/openy_gc_log.install
  modules/openy_gc_personal_training/openy_gc_personal_training.install
  modules/openy_gc_personal_training/openy_gc_personal_training.module
  modules/openy_gc_personal_training/openy_gc_personal_training.services.yml
  modules/openy_gc_personal_training/src/PersonalTrainingSeriesManager.php
  modules/openy_gc_shared_content/openy_gc_shared_content.install
  modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
  modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
  modules/openy_gc_storage/openy_gc_storage.install
  openy_gated_content.install
  openy_gated_content.module
  src/Form/RebuildDurationsForm.php
Labels: REBUILD

#436 Update bundle_field_map
  modules/openy_gc_shared_content/openy_gc_shared_content.module
  openy_gated_content.module
Labels: TESTED

#431 Record VY login to Daxko Virtual Branch
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/install/openy_gc_auth.provider.daxko_sso.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.services.yml
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/EventSubscriber/GCAuthDaxkoSsoLoginSubscriber.php
  modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Plugin/GCIdentityProvider/DaxkoSSO.php
Labels: TESTED, REBUILD
